### ISSUE TITLE
Doesn't work with latest SF build

### ISSUE THREAD

**Issue by galoti** [Zerthick/CommandBooks#2]
No errors on console, but when I left-click the book nothing happens. SF3616

**Comment by Zerthick** [comment]
See if this version works: https://github.com/Zerthick/CommandBooks/releases/tag/v1.6.1 :smiley:

**Comment by galoti** [comment]
It works, but only with 1 command.

**Comment by Zerthick** [comment]
You're right! Try this version instead: https://github.com/Zerthick/CommandBooks/releases/tag/v1.6.2

**Comment by galoti** [comment]
It's ok now, thanks

**Comment by Zerthick** [comment]
Great!
